### ISSUE TITLE
invalid connection

### ISSUE THREAD

**Issue by vitaly-t** [Jtimes3/juju#127]
from this file: https://github.com/Jtimes3/juju/blob/develop/server/cronJobs.js

```js
var pgp = require('pg-promise')
var connectionString = process.env.DATABASE_URL;
var db = pgp(connectionString);
```

that's invalid, should be:

```js
var pgp = require('pg-promise')({
// initialization options.
});
var connectionString = process.env.DATABASE_URL;
var db = pgp(connectionString);
```

You really should place all connection details in a single shared module to avoid such a mess.

**Comment by eternal44** [comment]
Thanks for the feedback!  I just refactored that connection into a module.

**Comment by vitaly-t** [comment]
You are welcome!
